# Default values for zookeeper-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: amuraru/zookeeper-operator
  tag: v0.2.6-adobe-2
  pullPolicy: IfNotPresent

## Install RBAC roles and bindings
rbac:
  create: true

## Service account names and whether to create them
serviceAccount:
  create: true
  name: zookeeper-operator

# Whether to create custom resource
crd:
  create: true

#
# Specifies which namespace(s) the Operator should watch for new ClusterResource resources
# Default: "" == Watch ALL namespaces
# Multiple namespaces can be configured using a comma separated list of namespaces
watchNamespace: ""
